### ISSUE TITLE
Consider using math/bits.OnesCount64 for computing Hamming distance

### ISSUE THREAD

**Issue by dominikh** [corona10/goimagehash#10]
math/bits contains optimized bit operations, which additionally are treated as intrinsics when platform support exists. For example, on modern x86 platforms, OnesCount64 will use the POPCNT instruction, and on unsupported platforms, it'll still use an implementation more efficient than shifting 63 times.

**Comment by corona10** [comment]
@dominikh 
Thanks for your issuing.
I will update this module on this weekend or you can send me a pull request :)
Do you want to try it?

**Comment by dominikh** [comment]
Sure, I'll send a PR later today.
