### ISSUE TITLE
Migrate package manager into Go 1.11 Modules

### ISSUE THREAD

**Issue by corona10** [corona10/goimagehash#17]
https://github.com/golang/go/wiki/Modules was announced.
goimagehash should migrate it when the timing is proper.

**Comment by navossoc** [comment]
Hi, is there any special reason to use this specific version of `github.com/nfnt/resize`?
https://github.com/corona10/goimagehash/blob/8be960c20e75eb3cc7943b4bf30147d470f20016/go.mod#L3

Current version is:
> v0.0.0-20180221191011-83c6a9932646

**Comment by corona10** [comment]
@navossoc 
No practical reason for that :)
PR would be welcomed.
I wonder know there was performance enhancmemt within resizing.
