### ISSUE TITLE
[Question] Are the hashes safe to use in goroutines?

### ISSUE THREAD

**Issue by kvnxiao** [corona10/goimagehash#42]
Just wondering if it is safe to start up a bunch of "worker threads" in many different goroutines to concurrently compute image differences to find an image match, or if I must do it sequentially.

For example, I have 1 image that matches out of a database list of 100 images with only one correct match in the database. And I need to check through all these images to find the one with the smallest score.

**Comment by corona10** [comment]
@kvnxiao 

Hmm you mean

gorutine-0: image0 vs image1
gorutine-0: image0 vs image1
gorutine-0: image0 vs image1
gorutine-0: image0 vs image1

**Comment by corona10** [comment]
@kvnxiao IMHO it will be safe to use hash multiple goroutine if the target image hash is precomputed.
